name: Build and Test GitHub actions

on:
  push:
    branches:
    - master
    - dev
    - release/*

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        dotnet: [ '3.1.100' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build console app
      shell: bash
      run: |
        dotnet build

    - name: Test console app
      shell: bash
      run: |
        dotnet test test/**/*.csproj

    - name: Run the private action
      uses: ./
      with:
        webhook_uri: ${{ secrets.WEBHOOK_URI }}
        title: ''
        summary: 'GitHub Actions Message'
        text: ''
        theme_color: ''
        sections: '[{ "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "GitHub Action invoked",  "activitySubtitle": "Event triggered by ${{ github.event.head_commit.author.name }}", "activityText": "Commit message: [${{ github.event.head_commit.message}}](${{ github.event.head_commit.url }})" }]'
        actions: '[{ "@type": "OpenUri", "name": "View Commit", "targets": [{ "os": "default", "uri": "${{ github.event.head_commit.url }}" }] }]'
